services:
    mysql:
        image: mysql:8.0.34
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - mysql-data:/var/lib/mysql

    php:
        build:
            context: .
            dockerfile: php.dockerfile
        ports:
            - '80:80'
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - /var/www/html/vendor # Prevents vendor from being overwritten by the host
        depends_on:
            - mysql
    node:
        build:
            context: .
            dockerfile: node.dockerfile
        # working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - /var/www/html/node_modules # Prevents node_modules from being overwritten by the host
        entrypoint: ['npm', 'run', 'build']
        depends_on:
            - php
volumes:
    mysql-data:
